# frozen_string_literal: true
ruby '2.6.3'

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem 'rack', '~> 2.0'
gem 'puma', '~> 4.0', '>= 4.0.1'
